name:                text-editor
version:             0.0.0.0
github:              "NorfairKing/writing-a-text-editor-in-haskell-with-brick"
license:             MIT

dependencies:
- base < 5

library:
  source-dirs: src
  dependencies:
  - brick
  - cursor
  - cursor-brick
  - directory
  - path
  - path-io
  - pretty-show
  - text
  - vty

executables:
  text-editor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-editor
